name: Cloudflare Pages

permissions:
  contents: read
  deployments: write

on: push

jobs:
  cloudflare-pages:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: volta-cli/action@v4.0.0
      - run: |
          npm ci
          npm run build
      - uses: cloudflare/pages-action@v1.3.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 9839aabb4253ed85d80549a8f99ee832
          projectName: steamredesign
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
