name: Prettier

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - uses: volta-cli/action@v4.0.0
      - name: Prettier Action
        uses: creyD/prettier_action@v4.3
        with:
          prettier_version: 2.8.4
          prettier_options: --write .
          file_pattern: .
          prettier_plugins: prettier-plugin-astro
